#!/usr/bin/env bash
# =============================================================================
# env-gen.sh — Generate .env file for a given environment from config.json
#              and merge with existing secrets in envs/<env>/.env
# Usage: ./scripts/env-gen.sh <env>
# =============================================================================

source "$(dirname "$0")/lib.sh"
require_cmd jq

ENV="${1:-}"
[[ -n "$ENV" ]] || die "Usage: env-gen.sh <env>"
validate_env "$ENV"

log_section "Generating .env for '$ENV'"

OUT_DIR="$(env_dir "$ENV")"
OUT_FILE="$OUT_DIR/.env"
EXAMPLE_FILE="$OUT_DIR/.env.example"
PROJECT_TYPE="$(cfg_get '.project.type // "custom"')"
PROJECT="$(cfg_get '.project.name')"

mkdir -p "$OUT_DIR"

# ── Image stack: .env is simply the env_vars collected per environment ─────────
# These are the actual secret/path values that the compose environment: blocks
# reference via ${VAR} interpolation (e.g. MYSQL_PASSWORD=secret, WP_PORT=8080).
if [[ "$PROJECT_TYPE" == "image" ]]; then
  cat > "$OUT_FILE" <<EOF
# ============================================================
# Auto-generated by env-gen.sh — $(date -u '+%Y-%m-%d %H:%M:%S UTC')
# Environment: $ENV  |  Project: $PROJECT  (type: image)
# Edit this file to update secrets. DO NOT COMMIT.
# Regenerate (resets to config.json values): ./run.sh init $ENV --regen-env
# ============================================================

EOF

  # Write KEY=VALUE pairs from config.json environments[ENV].env_vars
  jq -r ".environments.${ENV}.env_vars // {} | to_entries[] | \"\(.key)=\(.value)\"" \
    "$CONFIG_FILE" >> "$OUT_FILE" 2>/dev/null || true

  # .env.example is the same file — no auto-generated secrets to redact
  cp "$OUT_FILE" "$EXAMPLE_FILE"

  log_success ".env written to $OUT_FILE"
  log_success ".env.example written to $EXAMPLE_FILE"
  exit 0
fi

# ── Custom stack: full generation below ───────────────────────────────────────

# ── Pull values from config (custom stack) ───────────────────────────────────
REGISTRY="$(cfg_get '.project.registry')"
VERSION="$(version_string)"
TAG="${VERSION}-${ENV}"

DOMAIN="$(cfg_env_get "$ENV" '.domain')"
HTTP_PORT="$(cfg_env_get "$ENV" '.http_port')"
HTTPS_PORT="$(cfg_env_get "$ENV" '.https_port')"
BACKEND="$(cfg_env_get "$ENV" '.backend')"
FRONTEND_ENABLED="$(cfg_env_get "$ENV" '.frontend_enabled')"
FRONTEND="$(cfg_env_get "$ENV" '.frontend')"
DATABASE="$(cfg_env_get "$ENV" '.database')"
REDIS_ENABLED="$(cfg_env_get "$ENV" '.redis_enabled')"
GARAGE_ENABLED="$(cfg_env_get "$ENV" '.garage_enabled')"
TRAEFIK_ENABLED="$(cfg_env_get "$ENV" '.traefik_enabled')"
DEPLOYMENT="$(cfg_env_get "$ENV" '.deployment')"
BACKEND_REPLICAS="$(cfg_env_get "$ENV" '.replicas.backend')"
FRONTEND_REPLICAS="$(cfg_env_get "$ENV" '.replicas.frontend')"

PREFIX="${PROJECT}_${ENV}"

# ── Load existing secret values if .env already exists ───────────────────────
get_existing() {
  local key="$1"
  local default="${2:-}"
  if [[ -f "$OUT_FILE" ]]; then
    local val
    val="$(grep -E "^${key}=" "$OUT_FILE" 2>/dev/null | cut -d= -f2- | head -1)"
    echo "${val:-$default}"
  else
    echo "$default"
  fi
}

# Pre-load secrets so they survive regeneration
# Uppercase PREFIX without Bash 4+ ${^^} — use tr
PREFIX_UPPER="$(echo "$PREFIX" | tr '[:lower:]' '[:upper:]')"
DB_PASSWORD="$(get_existing "${PREFIX_UPPER}_DB_PASSWORD" "changeme_$(openssl rand -hex 8)")"
DB_ROOT_PASSWORD="$(get_existing "${PREFIX_UPPER}_DB_ROOT_PASSWORD" "changeme_$(openssl rand -hex 8)")"
APP_KEY="$(get_existing "${PREFIX_UPPER}_APP_KEY" "base64:$(openssl rand -base64 32)")"
GARAGE_ADMIN_TOKEN="$(get_existing "${PREFIX_UPPER}_GARAGE_ADMIN_TOKEN" "$(openssl rand -hex 16)")"
GARAGE_KEY_ID="$(get_existing "${PREFIX_UPPER}_GARAGE_KEY_ID" "$(openssl rand -hex 8)")"
GARAGE_SECRET_KEY="$(get_existing "${PREFIX_UPPER}_GARAGE_SECRET_KEY" "$(openssl rand -hex 32)")"

# ── Write .env ─────────────────────────────────────────────────────────────────
cat > "$OUT_FILE" <<EOF
# ============================================================
# Auto-generated by env-gen.sh — $(date -u '+%Y-%m-%d %H:%M:%S UTC')
# Environment: $ENV  |  Project: $PROJECT
# DO NOT COMMIT — contains secrets
# ============================================================

# ── Project ────────────────────────────────────────────────
COMPOSE_PROJECT_NAME=${PREFIX}
PROJECT_NAME=${PROJECT}
ENV=${ENV}

# ── Image tags ─────────────────────────────────────────────
REGISTRY=${REGISTRY}
IMAGE_TAG=${TAG}
BACKEND_IMAGE=${REGISTRY}/${PROJECT}-backend:${TAG}
$(if [[ "$FRONTEND_ENABLED" == "true" ]]; then echo "FRONTEND_IMAGE=${REGISTRY}/${PROJECT}-frontend:${TAG}"; fi)

# ── Domain & ports ─────────────────────────────────────────
DOMAIN=${DOMAIN}
HTTP_PORT=${HTTP_PORT}
HTTPS_PORT=${HTTPS_PORT}

# ── Stack config ────────────────────────────────────────────
BACKEND=${BACKEND}
FRONTEND=${FRONTEND}
FRONTEND_ENABLED=${FRONTEND_ENABLED}
DEPLOYMENT=${DEPLOYMENT}
TRAEFIK_ENABLED=${TRAEFIK_ENABLED}
BACKEND_REPLICAS=${BACKEND_REPLICAS}
FRONTEND_REPLICAS=${FRONTEND_REPLICAS}

# ── Database ───────────────────────────────────────────────
DATABASE=${DATABASE}
$(if [[ "$DATABASE" == "postgres" ]]; then
cat <<PGENV
POSTGRES_HOST=${PREFIX}_postgres
POSTGRES_PORT=5432
POSTGRES_DB=${PROJECT}_${ENV}
POSTGRES_USER=${PROJECT}_user
POSTGRES_PASSWORD=${DB_PASSWORD}
PGENV
elif [[ "$DATABASE" == "mysql" ]]; then
cat <<MYENV
MYSQL_HOST=${PREFIX}_mysql
MYSQL_PORT=3306
MYSQL_DATABASE=${PROJECT}_${ENV}
MYSQL_USER=${PROJECT}_user
MYSQL_PASSWORD=${DB_PASSWORD}
MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
MYENV
fi)

# ── Application ────────────────────────────────────────────
APP_ENV=${ENV}
APP_DEBUG=$(if [[ "$ENV" == "dev" ]]; then echo "true"; else echo "false"; fi)
APP_URL=http://${DOMAIN}
APP_KEY=${APP_KEY}

# ── Redis ──────────────────────────────────────────────────
REDIS_ENABLED=${REDIS_ENABLED}
$(if [[ "$REDIS_ENABLED" == "true" ]]; then
cat <<RENV
REDIS_HOST=${PREFIX}_redis
REDIS_PORT=6379
REDIS_PASSWORD=
RENV
fi)

# ── Garage (S3-compatible storage) ─────────────────────────
GARAGE_ENABLED=${GARAGE_ENABLED}
$(if [[ "$GARAGE_ENABLED" == "true" ]]; then
cat <<GENV
GARAGE_HOST=${PREFIX}_garage
GARAGE_API_PORT=3900
GARAGE_S3_PORT=3901
GARAGE_WEB_PORT=3903
GARAGE_ADMIN_TOKEN=${GARAGE_ADMIN_TOKEN}
GARAGE_KEY_ID=${GARAGE_KEY_ID}
GARAGE_SECRET_KEY=${GARAGE_SECRET_KEY}
GARAGE_BUCKET=${PROJECT}-${ENV}
GARAGE_ENDPOINT=http://${PREFIX}_garage:3901
GENV
fi)

# ── Mail (fill in per-environment) ─────────────────────────
MAIL_DRIVER=smtp
MAIL_HOST=mailhog
MAIL_PORT=1025
MAIL_USERNAME=
MAIL_PASSWORD=
MAIL_FROM_ADDRESS=noreply@${DOMAIN}
MAIL_FROM_NAME="${PROJECT}"

# ── Node.js specific ───────────────────────────────────────
NODE_ENV=$(if [[ "$ENV" == "prod" ]]; then echo "production"; else echo "development"; fi)
PORT=3000
EOF

log_success ".env written to $OUT_FILE"

# ── Append extra env_vars from config.json (wizard-collected, custom type) ────
_extra_vars="$(jq -r ".environments.${ENV}.env_vars // {} | to_entries[] | \"\(.key)=\(.value)\"" \
  "$CONFIG_FILE" 2>/dev/null || true)"
if [[ -n "$_extra_vars" ]]; then
  echo >> "$OUT_FILE"
  echo "# ── Extra variables (from config.json env_vars) ───────────────────" >> "$OUT_FILE"
  echo "$_extra_vars" >> "$OUT_FILE"
  log_info "Appended $(echo "$_extra_vars" | wc -l | tr -d ' ') extra env_var(s) to .env"
fi

# ── Write .env.example (no real secrets) ─────────────────────────────────────
sed \
  -e "s/${DB_PASSWORD}/CHANGE_ME_DB_PASSWORD/g" \
  -e "s/${DB_ROOT_PASSWORD}/CHANGE_ME_ROOT_PASSWORD/g" \
  -e "s/${GARAGE_ADMIN_TOKEN}/CHANGE_ME_GARAGE_TOKEN/g" \
  -e "s/${GARAGE_KEY_ID}/CHANGE_ME_KEY_ID/g" \
  -e "s/${GARAGE_SECRET_KEY}/CHANGE_ME_SECRET_KEY/g" \
  "$OUT_FILE" | grep -v '^APP_KEY=' | sed "s/^APP_KEY=.*/APP_KEY=base64:CHANGE_ME/" \
  > "$EXAMPLE_FILE"

log_success ".env.example written to $EXAMPLE_FILE"
